# -*- coding: utf-8 -*-
"""eye_tree_eyeglasses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12DQmXJXMaeKgx7hI-JqFFsdER5a0JFxn

# **Eye tree eyeglasses Detection using OpenCV**

Import cv2 library
"""

import cv2

"""**haarcascade_eye_tree_eyeglasses.xml** is a haar cascade designed by OpenCV. It's an eye detector with better handling of eyeglasses."""

!pip install wget
import requests
import wget
url = 'https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_eye_tree_eyeglasses.xml'
filename = wget.download(url)

face = cv2.CascadeClassifier(cv2.data.haarcascades + filename)

def detect(gray, frame):
  faces = face.detectMultiScale(gray, 1.3, 5)
  for (x, y , w, h) in faces:
    cv2.rectangle(frame, (x,y), (x+w, y+h), (255, 0 , 0), 3)
    roi_gray = gray[y:y+h, x:x+w]
  return frame

# Uncomment below code to open webcam and run in terminal
"""
video_capture = cv2.VideoCapture(0)
print(video_capture.isOpened())
while True:
  _, frame = video_capture.read()
  gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
  canvas = detect(gray, frame)
  cv2.imshow("Video", canvas)

  if cv2.waitkey(1) & 0xFF == ord('q'):
   break

video_capture.release()
cv2.destroyAllWindows()
"""

from google.colab.patches import cv2_imshow
img_url = 'https://data.whicdn.com/images/77156718/original.jpg'
image = wget.download(img_url)
image = cv2.imread(image)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
canvas = detect(gray, image)
cv2_imshow(canvas)

